package com.uyoung.core.api.model;

import java.util.Date;

public class ActivitySignUp {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_activity_signup.id
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_activity_signup.activity_id
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    private Integer activityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_activity_signup.user_id
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_activity_signup.status
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_activity_signup.create_time
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_activity_signup.update_time
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_activity_signup.id
     *
     * @return the value of tb_activity_signup.id
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_activity_signup.id
     *
     * @param id the value for tb_activity_signup.id
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_activity_signup.activity_id
     *
     * @return the value of tb_activity_signup.activity_id
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    public Integer getActivityId() {
        return activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_activity_signup.activity_id
     *
     * @param activityId the value for tb_activity_signup.activity_id
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    public void setActivityId(Integer activityId) {
        this.activityId = activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_activity_signup.user_id
     *
     * @return the value of tb_activity_signup.user_id
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_activity_signup.user_id
     *
     * @param userId the value for tb_activity_signup.user_id
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_activity_signup.status
     *
     * @return the value of tb_activity_signup.status
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_activity_signup.status
     *
     * @param status the value for tb_activity_signup.status
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_activity_signup.create_time
     *
     * @return the value of tb_activity_signup.create_time
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_activity_signup.create_time
     *
     * @param createTime the value for tb_activity_signup.create_time
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_activity_signup.update_time
     *
     * @return the value of tb_activity_signup.update_time
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_activity_signup.update_time
     *
     * @param updateTime the value for tb_activity_signup.update_time
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}