package com.uyoung.core.api.model;

import java.util.Date;

public class ActivityInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_activity_info.id
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_activity_info.title
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_activity_info.ori_user_id
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    private Integer oriUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_activity_info.begin_time
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    private Date beginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_activity_info.end_time
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_activity_info.address
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_activity_info.need_num
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    private Integer needNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_activity_info.real_num
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    private Integer realNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_activity_info.activity_type
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    private Byte activityType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_activity_info.fee_type
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    private Boolean feeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_activity_info.descripition
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    private String descripition;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_activity_info.status
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    private Boolean status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_activity_info.create_time
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_activity_info.update_time
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_activity_info.id
     *
     * @return the value of tb_activity_info.id
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_activity_info.id
     *
     * @param id the value for tb_activity_info.id
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_activity_info.title
     *
     * @return the value of tb_activity_info.title
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_activity_info.title
     *
     * @param title the value for tb_activity_info.title
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_activity_info.ori_user_id
     *
     * @return the value of tb_activity_info.ori_user_id
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    public Integer getOriUserId() {
        return oriUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_activity_info.ori_user_id
     *
     * @param oriUserId the value for tb_activity_info.ori_user_id
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    public void setOriUserId(Integer oriUserId) {
        this.oriUserId = oriUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_activity_info.begin_time
     *
     * @return the value of tb_activity_info.begin_time
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    public Date getBeginTime() {
        return beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_activity_info.begin_time
     *
     * @param beginTime the value for tb_activity_info.begin_time
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    public void setBeginTime(Date beginTime) {
        this.beginTime = beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_activity_info.end_time
     *
     * @return the value of tb_activity_info.end_time
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_activity_info.end_time
     *
     * @param endTime the value for tb_activity_info.end_time
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_activity_info.address
     *
     * @return the value of tb_activity_info.address
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_activity_info.address
     *
     * @param address the value for tb_activity_info.address
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_activity_info.need_num
     *
     * @return the value of tb_activity_info.need_num
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    public Integer getNeedNum() {
        return needNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_activity_info.need_num
     *
     * @param needNum the value for tb_activity_info.need_num
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    public void setNeedNum(Integer needNum) {
        this.needNum = needNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_activity_info.real_num
     *
     * @return the value of tb_activity_info.real_num
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    public Integer getRealNum() {
        return realNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_activity_info.real_num
     *
     * @param realNum the value for tb_activity_info.real_num
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    public void setRealNum(Integer realNum) {
        this.realNum = realNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_activity_info.activity_type
     *
     * @return the value of tb_activity_info.activity_type
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    public Byte getActivityType() {
        return activityType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_activity_info.activity_type
     *
     * @param activityType the value for tb_activity_info.activity_type
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    public void setActivityType(Byte activityType) {
        this.activityType = activityType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_activity_info.fee_type
     *
     * @return the value of tb_activity_info.fee_type
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    public Boolean getFeeType() {
        return feeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_activity_info.fee_type
     *
     * @param feeType the value for tb_activity_info.fee_type
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    public void setFeeType(Boolean feeType) {
        this.feeType = feeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_activity_info.descripition
     *
     * @return the value of tb_activity_info.descripition
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    public String getDescripition() {
        return descripition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_activity_info.descripition
     *
     * @param descripition the value for tb_activity_info.descripition
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    public void setDescripition(String descripition) {
        this.descripition = descripition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_activity_info.status
     *
     * @return the value of tb_activity_info.status
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_activity_info.status
     *
     * @param status the value for tb_activity_info.status
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_activity_info.create_time
     *
     * @return the value of tb_activity_info.create_time
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_activity_info.create_time
     *
     * @param createTime the value for tb_activity_info.create_time
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_activity_info.update_time
     *
     * @return the value of tb_activity_info.update_time
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_activity_info.update_time
     *
     * @param updateTime the value for tb_activity_info.update_time
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}