package com.uyoung.core.api.model;

import java.util.Date;

public class AlbumInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_album_info.id
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_album_info.title
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_album_info.create_user_id
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    private Integer createUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_album_info.album_name
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    private String albumName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_album_info.album_url
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    private String albumUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_album_info.first_photo_url
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    private String firstPhotoUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_album_info.create_time
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_album_info.update_time
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_album_info.id
     *
     * @return the value of tb_album_info.id
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_album_info.id
     *
     * @param id the value for tb_album_info.id
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_album_info.title
     *
     * @return the value of tb_album_info.title
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_album_info.title
     *
     * @param title the value for tb_album_info.title
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_album_info.create_user_id
     *
     * @return the value of tb_album_info.create_user_id
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    public Integer getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_album_info.create_user_id
     *
     * @param createUserId the value for tb_album_info.create_user_id
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    public void setCreateUserId(Integer createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_album_info.album_name
     *
     * @return the value of tb_album_info.album_name
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    public String getAlbumName() {
        return albumName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_album_info.album_name
     *
     * @param albumName the value for tb_album_info.album_name
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    public void setAlbumName(String albumName) {
        this.albumName = albumName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_album_info.album_url
     *
     * @return the value of tb_album_info.album_url
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    public String getAlbumUrl() {
        return albumUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_album_info.album_url
     *
     * @param albumUrl the value for tb_album_info.album_url
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    public void setAlbumUrl(String albumUrl) {
        this.albumUrl = albumUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_album_info.first_photo_url
     *
     * @return the value of tb_album_info.first_photo_url
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    public String getFirstPhotoUrl() {
        return firstPhotoUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_album_info.first_photo_url
     *
     * @param firstPhotoUrl the value for tb_album_info.first_photo_url
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    public void setFirstPhotoUrl(String firstPhotoUrl) {
        this.firstPhotoUrl = firstPhotoUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_album_info.create_time
     *
     * @return the value of tb_album_info.create_time
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_album_info.create_time
     *
     * @param createTime the value for tb_album_info.create_time
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_album_info.update_time
     *
     * @return the value of tb_album_info.update_time
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_album_info.update_time
     *
     * @param updateTime the value for tb_album_info.update_time
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}