package com.uyoung.core.api.model;

import java.util.Date;

public class MobileInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_mobile_info.id
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_mobile_info.platform
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    private Boolean platform;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_mobile_info.version
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    private String version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_mobile_info.token
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    private String token;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_mobile_info.imei
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    private String imei;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_mobile_info.user_id
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_mobile_info.validate
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    private Byte validate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_mobile_info.create_time
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_mobile_info.update_time
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_mobile_info.id
     *
     * @return the value of tb_mobile_info.id
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_mobile_info.id
     *
     * @param id the value for tb_mobile_info.id
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_mobile_info.platform
     *
     * @return the value of tb_mobile_info.platform
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    public Boolean getPlatform() {
        return platform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_mobile_info.platform
     *
     * @param platform the value for tb_mobile_info.platform
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    public void setPlatform(Boolean platform) {
        this.platform = platform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_mobile_info.version
     *
     * @return the value of tb_mobile_info.version
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_mobile_info.version
     *
     * @param version the value for tb_mobile_info.version
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    public void setVersion(String version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_mobile_info.token
     *
     * @return the value of tb_mobile_info.token
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_mobile_info.token
     *
     * @param token the value for tb_mobile_info.token
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    public void setToken(String token) {
        this.token = token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_mobile_info.imei
     *
     * @return the value of tb_mobile_info.imei
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    public String getImei() {
        return imei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_mobile_info.imei
     *
     * @param imei the value for tb_mobile_info.imei
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    public void setImei(String imei) {
        this.imei = imei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_mobile_info.user_id
     *
     * @return the value of tb_mobile_info.user_id
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_mobile_info.user_id
     *
     * @param userId the value for tb_mobile_info.user_id
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_mobile_info.validate
     *
     * @return the value of tb_mobile_info.validate
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    public Byte getValidate() {
        return validate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_mobile_info.validate
     *
     * @param validate the value for tb_mobile_info.validate
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    public void setValidate(Byte validate) {
        this.validate = validate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_mobile_info.create_time
     *
     * @return the value of tb_mobile_info.create_time
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_mobile_info.create_time
     *
     * @param createTime the value for tb_mobile_info.create_time
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_mobile_info.update_time
     *
     * @return the value of tb_mobile_info.update_time
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_mobile_info.update_time
     *
     * @param updateTime the value for tb_mobile_info.update_time
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}