package com.uyoung.core.api.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class PhotoInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_photo_info
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_photo_info
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_photo_info
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_photo_info
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    public PhotoInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_photo_info
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_photo_info
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_photo_info
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_photo_info
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_photo_info
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_photo_info
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_photo_info
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_photo_info
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_photo_info
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_photo_info
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_photo_info
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andPhotoNameIsNull() {
            addCriterion("photo_name is null");
            return (Criteria) this;
        }

        public Criteria andPhotoNameIsNotNull() {
            addCriterion("photo_name is not null");
            return (Criteria) this;
        }

        public Criteria andPhotoNameEqualTo(String value) {
            addCriterion("photo_name =", value, "photoName");
            return (Criteria) this;
        }

        public Criteria andPhotoNameNotEqualTo(String value) {
            addCriterion("photo_name <>", value, "photoName");
            return (Criteria) this;
        }

        public Criteria andPhotoNameGreaterThan(String value) {
            addCriterion("photo_name >", value, "photoName");
            return (Criteria) this;
        }

        public Criteria andPhotoNameGreaterThanOrEqualTo(String value) {
            addCriterion("photo_name >=", value, "photoName");
            return (Criteria) this;
        }

        public Criteria andPhotoNameLessThan(String value) {
            addCriterion("photo_name <", value, "photoName");
            return (Criteria) this;
        }

        public Criteria andPhotoNameLessThanOrEqualTo(String value) {
            addCriterion("photo_name <=", value, "photoName");
            return (Criteria) this;
        }

        public Criteria andPhotoNameLike(String value) {
            addCriterion("photo_name like", value, "photoName");
            return (Criteria) this;
        }

        public Criteria andPhotoNameNotLike(String value) {
            addCriterion("photo_name not like", value, "photoName");
            return (Criteria) this;
        }

        public Criteria andPhotoNameIn(List<String> values) {
            addCriterion("photo_name in", values, "photoName");
            return (Criteria) this;
        }

        public Criteria andPhotoNameNotIn(List<String> values) {
            addCriterion("photo_name not in", values, "photoName");
            return (Criteria) this;
        }

        public Criteria andPhotoNameBetween(String value1, String value2) {
            addCriterion("photo_name between", value1, value2, "photoName");
            return (Criteria) this;
        }

        public Criteria andPhotoNameNotBetween(String value1, String value2) {
            addCriterion("photo_name not between", value1, value2, "photoName");
            return (Criteria) this;
        }

        public Criteria andPhotoDescIsNull() {
            addCriterion("photo_desc is null");
            return (Criteria) this;
        }

        public Criteria andPhotoDescIsNotNull() {
            addCriterion("photo_desc is not null");
            return (Criteria) this;
        }

        public Criteria andPhotoDescEqualTo(String value) {
            addCriterion("photo_desc =", value, "photoDesc");
            return (Criteria) this;
        }

        public Criteria andPhotoDescNotEqualTo(String value) {
            addCriterion("photo_desc <>", value, "photoDesc");
            return (Criteria) this;
        }

        public Criteria andPhotoDescGreaterThan(String value) {
            addCriterion("photo_desc >", value, "photoDesc");
            return (Criteria) this;
        }

        public Criteria andPhotoDescGreaterThanOrEqualTo(String value) {
            addCriterion("photo_desc >=", value, "photoDesc");
            return (Criteria) this;
        }

        public Criteria andPhotoDescLessThan(String value) {
            addCriterion("photo_desc <", value, "photoDesc");
            return (Criteria) this;
        }

        public Criteria andPhotoDescLessThanOrEqualTo(String value) {
            addCriterion("photo_desc <=", value, "photoDesc");
            return (Criteria) this;
        }

        public Criteria andPhotoDescLike(String value) {
            addCriterion("photo_desc like", value, "photoDesc");
            return (Criteria) this;
        }

        public Criteria andPhotoDescNotLike(String value) {
            addCriterion("photo_desc not like", value, "photoDesc");
            return (Criteria) this;
        }

        public Criteria andPhotoDescIn(List<String> values) {
            addCriterion("photo_desc in", values, "photoDesc");
            return (Criteria) this;
        }

        public Criteria andPhotoDescNotIn(List<String> values) {
            addCriterion("photo_desc not in", values, "photoDesc");
            return (Criteria) this;
        }

        public Criteria andPhotoDescBetween(String value1, String value2) {
            addCriterion("photo_desc between", value1, value2, "photoDesc");
            return (Criteria) this;
        }

        public Criteria andPhotoDescNotBetween(String value1, String value2) {
            addCriterion("photo_desc not between", value1, value2, "photoDesc");
            return (Criteria) this;
        }

        public Criteria andPhotoUrlIsNull() {
            addCriterion("photo_url is null");
            return (Criteria) this;
        }

        public Criteria andPhotoUrlIsNotNull() {
            addCriterion("photo_url is not null");
            return (Criteria) this;
        }

        public Criteria andPhotoUrlEqualTo(String value) {
            addCriterion("photo_url =", value, "photoUrl");
            return (Criteria) this;
        }

        public Criteria andPhotoUrlNotEqualTo(String value) {
            addCriterion("photo_url <>", value, "photoUrl");
            return (Criteria) this;
        }

        public Criteria andPhotoUrlGreaterThan(String value) {
            addCriterion("photo_url >", value, "photoUrl");
            return (Criteria) this;
        }

        public Criteria andPhotoUrlGreaterThanOrEqualTo(String value) {
            addCriterion("photo_url >=", value, "photoUrl");
            return (Criteria) this;
        }

        public Criteria andPhotoUrlLessThan(String value) {
            addCriterion("photo_url <", value, "photoUrl");
            return (Criteria) this;
        }

        public Criteria andPhotoUrlLessThanOrEqualTo(String value) {
            addCriterion("photo_url <=", value, "photoUrl");
            return (Criteria) this;
        }

        public Criteria andPhotoUrlLike(String value) {
            addCriterion("photo_url like", value, "photoUrl");
            return (Criteria) this;
        }

        public Criteria andPhotoUrlNotLike(String value) {
            addCriterion("photo_url not like", value, "photoUrl");
            return (Criteria) this;
        }

        public Criteria andPhotoUrlIn(List<String> values) {
            addCriterion("photo_url in", values, "photoUrl");
            return (Criteria) this;
        }

        public Criteria andPhotoUrlNotIn(List<String> values) {
            addCriterion("photo_url not in", values, "photoUrl");
            return (Criteria) this;
        }

        public Criteria andPhotoUrlBetween(String value1, String value2) {
            addCriterion("photo_url between", value1, value2, "photoUrl");
            return (Criteria) this;
        }

        public Criteria andPhotoUrlNotBetween(String value1, String value2) {
            addCriterion("photo_url not between", value1, value2, "photoUrl");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIsNull() {
            addCriterion("create_user_id is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIsNotNull() {
            addCriterion("create_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdEqualTo(Integer value) {
            addCriterion("create_user_id =", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotEqualTo(Integer value) {
            addCriterion("create_user_id <>", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdGreaterThan(Integer value) {
            addCriterion("create_user_id >", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("create_user_id >=", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLessThan(Integer value) {
            addCriterion("create_user_id <", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("create_user_id <=", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIn(List<Integer> values) {
            addCriterion("create_user_id in", values, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotIn(List<Integer> values) {
            addCriterion("create_user_id not in", values, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdBetween(Integer value1, Integer value2) {
            addCriterion("create_user_id between", value1, value2, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("create_user_id not between", value1, value2, "createUserId");
            return (Criteria) this;
        }

        public Criteria andExifCameraIsNull() {
            addCriterion("exif_camera is null");
            return (Criteria) this;
        }

        public Criteria andExifCameraIsNotNull() {
            addCriterion("exif_camera is not null");
            return (Criteria) this;
        }

        public Criteria andExifCameraEqualTo(String value) {
            addCriterion("exif_camera =", value, "exifCamera");
            return (Criteria) this;
        }

        public Criteria andExifCameraNotEqualTo(String value) {
            addCriterion("exif_camera <>", value, "exifCamera");
            return (Criteria) this;
        }

        public Criteria andExifCameraGreaterThan(String value) {
            addCriterion("exif_camera >", value, "exifCamera");
            return (Criteria) this;
        }

        public Criteria andExifCameraGreaterThanOrEqualTo(String value) {
            addCriterion("exif_camera >=", value, "exifCamera");
            return (Criteria) this;
        }

        public Criteria andExifCameraLessThan(String value) {
            addCriterion("exif_camera <", value, "exifCamera");
            return (Criteria) this;
        }

        public Criteria andExifCameraLessThanOrEqualTo(String value) {
            addCriterion("exif_camera <=", value, "exifCamera");
            return (Criteria) this;
        }

        public Criteria andExifCameraLike(String value) {
            addCriterion("exif_camera like", value, "exifCamera");
            return (Criteria) this;
        }

        public Criteria andExifCameraNotLike(String value) {
            addCriterion("exif_camera not like", value, "exifCamera");
            return (Criteria) this;
        }

        public Criteria andExifCameraIn(List<String> values) {
            addCriterion("exif_camera in", values, "exifCamera");
            return (Criteria) this;
        }

        public Criteria andExifCameraNotIn(List<String> values) {
            addCriterion("exif_camera not in", values, "exifCamera");
            return (Criteria) this;
        }

        public Criteria andExifCameraBetween(String value1, String value2) {
            addCriterion("exif_camera between", value1, value2, "exifCamera");
            return (Criteria) this;
        }

        public Criteria andExifCameraNotBetween(String value1, String value2) {
            addCriterion("exif_camera not between", value1, value2, "exifCamera");
            return (Criteria) this;
        }

        public Criteria andExifApertureIsNull() {
            addCriterion("exif_aperture is null");
            return (Criteria) this;
        }

        public Criteria andExifApertureIsNotNull() {
            addCriterion("exif_aperture is not null");
            return (Criteria) this;
        }

        public Criteria andExifApertureEqualTo(String value) {
            addCriterion("exif_aperture =", value, "exifAperture");
            return (Criteria) this;
        }

        public Criteria andExifApertureNotEqualTo(String value) {
            addCriterion("exif_aperture <>", value, "exifAperture");
            return (Criteria) this;
        }

        public Criteria andExifApertureGreaterThan(String value) {
            addCriterion("exif_aperture >", value, "exifAperture");
            return (Criteria) this;
        }

        public Criteria andExifApertureGreaterThanOrEqualTo(String value) {
            addCriterion("exif_aperture >=", value, "exifAperture");
            return (Criteria) this;
        }

        public Criteria andExifApertureLessThan(String value) {
            addCriterion("exif_aperture <", value, "exifAperture");
            return (Criteria) this;
        }

        public Criteria andExifApertureLessThanOrEqualTo(String value) {
            addCriterion("exif_aperture <=", value, "exifAperture");
            return (Criteria) this;
        }

        public Criteria andExifApertureLike(String value) {
            addCriterion("exif_aperture like", value, "exifAperture");
            return (Criteria) this;
        }

        public Criteria andExifApertureNotLike(String value) {
            addCriterion("exif_aperture not like", value, "exifAperture");
            return (Criteria) this;
        }

        public Criteria andExifApertureIn(List<String> values) {
            addCriterion("exif_aperture in", values, "exifAperture");
            return (Criteria) this;
        }

        public Criteria andExifApertureNotIn(List<String> values) {
            addCriterion("exif_aperture not in", values, "exifAperture");
            return (Criteria) this;
        }

        public Criteria andExifApertureBetween(String value1, String value2) {
            addCriterion("exif_aperture between", value1, value2, "exifAperture");
            return (Criteria) this;
        }

        public Criteria andExifApertureNotBetween(String value1, String value2) {
            addCriterion("exif_aperture not between", value1, value2, "exifAperture");
            return (Criteria) this;
        }

        public Criteria andExifFacusIsNull() {
            addCriterion("exif_facus is null");
            return (Criteria) this;
        }

        public Criteria andExifFacusIsNotNull() {
            addCriterion("exif_facus is not null");
            return (Criteria) this;
        }

        public Criteria andExifFacusEqualTo(String value) {
            addCriterion("exif_facus =", value, "exifFacus");
            return (Criteria) this;
        }

        public Criteria andExifFacusNotEqualTo(String value) {
            addCriterion("exif_facus <>", value, "exifFacus");
            return (Criteria) this;
        }

        public Criteria andExifFacusGreaterThan(String value) {
            addCriterion("exif_facus >", value, "exifFacus");
            return (Criteria) this;
        }

        public Criteria andExifFacusGreaterThanOrEqualTo(String value) {
            addCriterion("exif_facus >=", value, "exifFacus");
            return (Criteria) this;
        }

        public Criteria andExifFacusLessThan(String value) {
            addCriterion("exif_facus <", value, "exifFacus");
            return (Criteria) this;
        }

        public Criteria andExifFacusLessThanOrEqualTo(String value) {
            addCriterion("exif_facus <=", value, "exifFacus");
            return (Criteria) this;
        }

        public Criteria andExifFacusLike(String value) {
            addCriterion("exif_facus like", value, "exifFacus");
            return (Criteria) this;
        }

        public Criteria andExifFacusNotLike(String value) {
            addCriterion("exif_facus not like", value, "exifFacus");
            return (Criteria) this;
        }

        public Criteria andExifFacusIn(List<String> values) {
            addCriterion("exif_facus in", values, "exifFacus");
            return (Criteria) this;
        }

        public Criteria andExifFacusNotIn(List<String> values) {
            addCriterion("exif_facus not in", values, "exifFacus");
            return (Criteria) this;
        }

        public Criteria andExifFacusBetween(String value1, String value2) {
            addCriterion("exif_facus between", value1, value2, "exifFacus");
            return (Criteria) this;
        }

        public Criteria andExifFacusNotBetween(String value1, String value2) {
            addCriterion("exif_facus not between", value1, value2, "exifFacus");
            return (Criteria) this;
        }

        public Criteria andExifShutterIsNull() {
            addCriterion("exif_shutter is null");
            return (Criteria) this;
        }

        public Criteria andExifShutterIsNotNull() {
            addCriterion("exif_shutter is not null");
            return (Criteria) this;
        }

        public Criteria andExifShutterEqualTo(String value) {
            addCriterion("exif_shutter =", value, "exifShutter");
            return (Criteria) this;
        }

        public Criteria andExifShutterNotEqualTo(String value) {
            addCriterion("exif_shutter <>", value, "exifShutter");
            return (Criteria) this;
        }

        public Criteria andExifShutterGreaterThan(String value) {
            addCriterion("exif_shutter >", value, "exifShutter");
            return (Criteria) this;
        }

        public Criteria andExifShutterGreaterThanOrEqualTo(String value) {
            addCriterion("exif_shutter >=", value, "exifShutter");
            return (Criteria) this;
        }

        public Criteria andExifShutterLessThan(String value) {
            addCriterion("exif_shutter <", value, "exifShutter");
            return (Criteria) this;
        }

        public Criteria andExifShutterLessThanOrEqualTo(String value) {
            addCriterion("exif_shutter <=", value, "exifShutter");
            return (Criteria) this;
        }

        public Criteria andExifShutterLike(String value) {
            addCriterion("exif_shutter like", value, "exifShutter");
            return (Criteria) this;
        }

        public Criteria andExifShutterNotLike(String value) {
            addCriterion("exif_shutter not like", value, "exifShutter");
            return (Criteria) this;
        }

        public Criteria andExifShutterIn(List<String> values) {
            addCriterion("exif_shutter in", values, "exifShutter");
            return (Criteria) this;
        }

        public Criteria andExifShutterNotIn(List<String> values) {
            addCriterion("exif_shutter not in", values, "exifShutter");
            return (Criteria) this;
        }

        public Criteria andExifShutterBetween(String value1, String value2) {
            addCriterion("exif_shutter between", value1, value2, "exifShutter");
            return (Criteria) this;
        }

        public Criteria andExifShutterNotBetween(String value1, String value2) {
            addCriterion("exif_shutter not between", value1, value2, "exifShutter");
            return (Criteria) this;
        }

        public Criteria andExifIsoIsNull() {
            addCriterion("exif_iso is null");
            return (Criteria) this;
        }

        public Criteria andExifIsoIsNotNull() {
            addCriterion("exif_iso is not null");
            return (Criteria) this;
        }

        public Criteria andExifIsoEqualTo(String value) {
            addCriterion("exif_iso =", value, "exifIso");
            return (Criteria) this;
        }

        public Criteria andExifIsoNotEqualTo(String value) {
            addCriterion("exif_iso <>", value, "exifIso");
            return (Criteria) this;
        }

        public Criteria andExifIsoGreaterThan(String value) {
            addCriterion("exif_iso >", value, "exifIso");
            return (Criteria) this;
        }

        public Criteria andExifIsoGreaterThanOrEqualTo(String value) {
            addCriterion("exif_iso >=", value, "exifIso");
            return (Criteria) this;
        }

        public Criteria andExifIsoLessThan(String value) {
            addCriterion("exif_iso <", value, "exifIso");
            return (Criteria) this;
        }

        public Criteria andExifIsoLessThanOrEqualTo(String value) {
            addCriterion("exif_iso <=", value, "exifIso");
            return (Criteria) this;
        }

        public Criteria andExifIsoLike(String value) {
            addCriterion("exif_iso like", value, "exifIso");
            return (Criteria) this;
        }

        public Criteria andExifIsoNotLike(String value) {
            addCriterion("exif_iso not like", value, "exifIso");
            return (Criteria) this;
        }

        public Criteria andExifIsoIn(List<String> values) {
            addCriterion("exif_iso in", values, "exifIso");
            return (Criteria) this;
        }

        public Criteria andExifIsoNotIn(List<String> values) {
            addCriterion("exif_iso not in", values, "exifIso");
            return (Criteria) this;
        }

        public Criteria andExifIsoBetween(String value1, String value2) {
            addCriterion("exif_iso between", value1, value2, "exifIso");
            return (Criteria) this;
        }

        public Criteria andExifIsoNotBetween(String value1, String value2) {
            addCriterion("exif_iso not between", value1, value2, "exifIso");
            return (Criteria) this;
        }

        public Criteria andExifOtherIsNull() {
            addCriterion("exif_other is null");
            return (Criteria) this;
        }

        public Criteria andExifOtherIsNotNull() {
            addCriterion("exif_other is not null");
            return (Criteria) this;
        }

        public Criteria andExifOtherEqualTo(String value) {
            addCriterion("exif_other =", value, "exifOther");
            return (Criteria) this;
        }

        public Criteria andExifOtherNotEqualTo(String value) {
            addCriterion("exif_other <>", value, "exifOther");
            return (Criteria) this;
        }

        public Criteria andExifOtherGreaterThan(String value) {
            addCriterion("exif_other >", value, "exifOther");
            return (Criteria) this;
        }

        public Criteria andExifOtherGreaterThanOrEqualTo(String value) {
            addCriterion("exif_other >=", value, "exifOther");
            return (Criteria) this;
        }

        public Criteria andExifOtherLessThan(String value) {
            addCriterion("exif_other <", value, "exifOther");
            return (Criteria) this;
        }

        public Criteria andExifOtherLessThanOrEqualTo(String value) {
            addCriterion("exif_other <=", value, "exifOther");
            return (Criteria) this;
        }

        public Criteria andExifOtherLike(String value) {
            addCriterion("exif_other like", value, "exifOther");
            return (Criteria) this;
        }

        public Criteria andExifOtherNotLike(String value) {
            addCriterion("exif_other not like", value, "exifOther");
            return (Criteria) this;
        }

        public Criteria andExifOtherIn(List<String> values) {
            addCriterion("exif_other in", values, "exifOther");
            return (Criteria) this;
        }

        public Criteria andExifOtherNotIn(List<String> values) {
            addCriterion("exif_other not in", values, "exifOther");
            return (Criteria) this;
        }

        public Criteria andExifOtherBetween(String value1, String value2) {
            addCriterion("exif_other between", value1, value2, "exifOther");
            return (Criteria) this;
        }

        public Criteria andExifOtherNotBetween(String value1, String value2) {
            addCriterion("exif_other not between", value1, value2, "exifOther");
            return (Criteria) this;
        }

        public Criteria andViewCountIsNull() {
            addCriterion("view_count is null");
            return (Criteria) this;
        }

        public Criteria andViewCountIsNotNull() {
            addCriterion("view_count is not null");
            return (Criteria) this;
        }

        public Criteria andViewCountEqualTo(Integer value) {
            addCriterion("view_count =", value, "viewCount");
            return (Criteria) this;
        }

        public Criteria andViewCountNotEqualTo(Integer value) {
            addCriterion("view_count <>", value, "viewCount");
            return (Criteria) this;
        }

        public Criteria andViewCountGreaterThan(Integer value) {
            addCriterion("view_count >", value, "viewCount");
            return (Criteria) this;
        }

        public Criteria andViewCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("view_count >=", value, "viewCount");
            return (Criteria) this;
        }

        public Criteria andViewCountLessThan(Integer value) {
            addCriterion("view_count <", value, "viewCount");
            return (Criteria) this;
        }

        public Criteria andViewCountLessThanOrEqualTo(Integer value) {
            addCriterion("view_count <=", value, "viewCount");
            return (Criteria) this;
        }

        public Criteria andViewCountIn(List<Integer> values) {
            addCriterion("view_count in", values, "viewCount");
            return (Criteria) this;
        }

        public Criteria andViewCountNotIn(List<Integer> values) {
            addCriterion("view_count not in", values, "viewCount");
            return (Criteria) this;
        }

        public Criteria andViewCountBetween(Integer value1, Integer value2) {
            addCriterion("view_count between", value1, value2, "viewCount");
            return (Criteria) this;
        }

        public Criteria andViewCountNotBetween(Integer value1, Integer value2) {
            addCriterion("view_count not between", value1, value2, "viewCount");
            return (Criteria) this;
        }

        public Criteria andLikeCountIsNull() {
            addCriterion("like_count is null");
            return (Criteria) this;
        }

        public Criteria andLikeCountIsNotNull() {
            addCriterion("like_count is not null");
            return (Criteria) this;
        }

        public Criteria andLikeCountEqualTo(Integer value) {
            addCriterion("like_count =", value, "likeCount");
            return (Criteria) this;
        }

        public Criteria andLikeCountNotEqualTo(Integer value) {
            addCriterion("like_count <>", value, "likeCount");
            return (Criteria) this;
        }

        public Criteria andLikeCountGreaterThan(Integer value) {
            addCriterion("like_count >", value, "likeCount");
            return (Criteria) this;
        }

        public Criteria andLikeCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("like_count >=", value, "likeCount");
            return (Criteria) this;
        }

        public Criteria andLikeCountLessThan(Integer value) {
            addCriterion("like_count <", value, "likeCount");
            return (Criteria) this;
        }

        public Criteria andLikeCountLessThanOrEqualTo(Integer value) {
            addCriterion("like_count <=", value, "likeCount");
            return (Criteria) this;
        }

        public Criteria andLikeCountIn(List<Integer> values) {
            addCriterion("like_count in", values, "likeCount");
            return (Criteria) this;
        }

        public Criteria andLikeCountNotIn(List<Integer> values) {
            addCriterion("like_count not in", values, "likeCount");
            return (Criteria) this;
        }

        public Criteria andLikeCountBetween(Integer value1, Integer value2) {
            addCriterion("like_count between", value1, value2, "likeCount");
            return (Criteria) this;
        }

        public Criteria andLikeCountNotBetween(Integer value1, Integer value2) {
            addCriterion("like_count not between", value1, value2, "likeCount");
            return (Criteria) this;
        }

        public Criteria andCommentCountIsNull() {
            addCriterion("comment_count is null");
            return (Criteria) this;
        }

        public Criteria andCommentCountIsNotNull() {
            addCriterion("comment_count is not null");
            return (Criteria) this;
        }

        public Criteria andCommentCountEqualTo(Integer value) {
            addCriterion("comment_count =", value, "commentCount");
            return (Criteria) this;
        }

        public Criteria andCommentCountNotEqualTo(Integer value) {
            addCriterion("comment_count <>", value, "commentCount");
            return (Criteria) this;
        }

        public Criteria andCommentCountGreaterThan(Integer value) {
            addCriterion("comment_count >", value, "commentCount");
            return (Criteria) this;
        }

        public Criteria andCommentCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("comment_count >=", value, "commentCount");
            return (Criteria) this;
        }

        public Criteria andCommentCountLessThan(Integer value) {
            addCriterion("comment_count <", value, "commentCount");
            return (Criteria) this;
        }

        public Criteria andCommentCountLessThanOrEqualTo(Integer value) {
            addCriterion("comment_count <=", value, "commentCount");
            return (Criteria) this;
        }

        public Criteria andCommentCountIn(List<Integer> values) {
            addCriterion("comment_count in", values, "commentCount");
            return (Criteria) this;
        }

        public Criteria andCommentCountNotIn(List<Integer> values) {
            addCriterion("comment_count not in", values, "commentCount");
            return (Criteria) this;
        }

        public Criteria andCommentCountBetween(Integer value1, Integer value2) {
            addCriterion("comment_count between", value1, value2, "commentCount");
            return (Criteria) this;
        }

        public Criteria andCommentCountNotBetween(Integer value1, Integer value2) {
            addCriterion("comment_count not between", value1, value2, "commentCount");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_photo_info
     *
     * @mbggenerated do_not_delete_during_merge Sat Sep 19 17:42:07 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_photo_info
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}