package com.uyoung.core.api.model;

import java.util.Date;

public class PhotoInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_photo_info.id
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_photo_info.photo_name
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    private String photoName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_photo_info.photo_desc
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    private String photoDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_photo_info.photo_url
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    private String photoUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_photo_info.create_user_id
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    private Integer createUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_photo_info.exif_camera
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    private String exifCamera;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_photo_info.exif_aperture
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    private String exifAperture;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_photo_info.exif_facus
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    private String exifFacus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_photo_info.exif_shutter
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    private String exifShutter;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_photo_info.exif_iso
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    private String exifIso;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_photo_info.exif_other
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    private String exifOther;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_photo_info.view_count
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    private Integer viewCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_photo_info.like_count
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    private Integer likeCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_photo_info.comment_count
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    private Integer commentCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_photo_info.create_time
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_photo_info.update_time
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_photo_info.id
     *
     * @return the value of tb_photo_info.id
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_photo_info.id
     *
     * @param id the value for tb_photo_info.id
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_photo_info.photo_name
     *
     * @return the value of tb_photo_info.photo_name
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    public String getPhotoName() {
        return photoName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_photo_info.photo_name
     *
     * @param photoName the value for tb_photo_info.photo_name
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    public void setPhotoName(String photoName) {
        this.photoName = photoName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_photo_info.photo_desc
     *
     * @return the value of tb_photo_info.photo_desc
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    public String getPhotoDesc() {
        return photoDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_photo_info.photo_desc
     *
     * @param photoDesc the value for tb_photo_info.photo_desc
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    public void setPhotoDesc(String photoDesc) {
        this.photoDesc = photoDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_photo_info.photo_url
     *
     * @return the value of tb_photo_info.photo_url
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    public String getPhotoUrl() {
        return photoUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_photo_info.photo_url
     *
     * @param photoUrl the value for tb_photo_info.photo_url
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    public void setPhotoUrl(String photoUrl) {
        this.photoUrl = photoUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_photo_info.create_user_id
     *
     * @return the value of tb_photo_info.create_user_id
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    public Integer getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_photo_info.create_user_id
     *
     * @param createUserId the value for tb_photo_info.create_user_id
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    public void setCreateUserId(Integer createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_photo_info.exif_camera
     *
     * @return the value of tb_photo_info.exif_camera
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    public String getExifCamera() {
        return exifCamera;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_photo_info.exif_camera
     *
     * @param exifCamera the value for tb_photo_info.exif_camera
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    public void setExifCamera(String exifCamera) {
        this.exifCamera = exifCamera;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_photo_info.exif_aperture
     *
     * @return the value of tb_photo_info.exif_aperture
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    public String getExifAperture() {
        return exifAperture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_photo_info.exif_aperture
     *
     * @param exifAperture the value for tb_photo_info.exif_aperture
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    public void setExifAperture(String exifAperture) {
        this.exifAperture = exifAperture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_photo_info.exif_facus
     *
     * @return the value of tb_photo_info.exif_facus
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    public String getExifFacus() {
        return exifFacus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_photo_info.exif_facus
     *
     * @param exifFacus the value for tb_photo_info.exif_facus
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    public void setExifFacus(String exifFacus) {
        this.exifFacus = exifFacus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_photo_info.exif_shutter
     *
     * @return the value of tb_photo_info.exif_shutter
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    public String getExifShutter() {
        return exifShutter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_photo_info.exif_shutter
     *
     * @param exifShutter the value for tb_photo_info.exif_shutter
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    public void setExifShutter(String exifShutter) {
        this.exifShutter = exifShutter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_photo_info.exif_iso
     *
     * @return the value of tb_photo_info.exif_iso
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    public String getExifIso() {
        return exifIso;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_photo_info.exif_iso
     *
     * @param exifIso the value for tb_photo_info.exif_iso
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    public void setExifIso(String exifIso) {
        this.exifIso = exifIso;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_photo_info.exif_other
     *
     * @return the value of tb_photo_info.exif_other
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    public String getExifOther() {
        return exifOther;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_photo_info.exif_other
     *
     * @param exifOther the value for tb_photo_info.exif_other
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    public void setExifOther(String exifOther) {
        this.exifOther = exifOther;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_photo_info.view_count
     *
     * @return the value of tb_photo_info.view_count
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    public Integer getViewCount() {
        return viewCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_photo_info.view_count
     *
     * @param viewCount the value for tb_photo_info.view_count
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    public void setViewCount(Integer viewCount) {
        this.viewCount = viewCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_photo_info.like_count
     *
     * @return the value of tb_photo_info.like_count
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    public Integer getLikeCount() {
        return likeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_photo_info.like_count
     *
     * @param likeCount the value for tb_photo_info.like_count
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    public void setLikeCount(Integer likeCount) {
        this.likeCount = likeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_photo_info.comment_count
     *
     * @return the value of tb_photo_info.comment_count
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    public Integer getCommentCount() {
        return commentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_photo_info.comment_count
     *
     * @param commentCount the value for tb_photo_info.comment_count
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    public void setCommentCount(Integer commentCount) {
        this.commentCount = commentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_photo_info.create_time
     *
     * @return the value of tb_photo_info.create_time
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_photo_info.create_time
     *
     * @param createTime the value for tb_photo_info.create_time
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_photo_info.update_time
     *
     * @return the value of tb_photo_info.update_time
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_photo_info.update_time
     *
     * @param updateTime the value for tb_photo_info.update_time
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}