package com.uyoung.core.api.model;

import java.util.Date;

public class UserInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_info.id
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_info.real_name
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    private String realName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_info.nick_name
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    private String nickName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_info.password
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_info.email
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_info.gender
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    private Boolean gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_info.avatar_url
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    private String avatarUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_info.phone
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_info.address
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    private Integer address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_info.company
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    private String company;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_info.position
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    private String position;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_info.equipment
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    private String equipment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_info.style
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    private Byte style;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_info.create_time
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user_info.update_time
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_info.id
     *
     * @return the value of tb_user_info.id
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_info.id
     *
     * @param id the value for tb_user_info.id
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_info.real_name
     *
     * @return the value of tb_user_info.real_name
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_info.real_name
     *
     * @param realName the value for tb_user_info.real_name
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    public void setRealName(String realName) {
        this.realName = realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_info.nick_name
     *
     * @return the value of tb_user_info.nick_name
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_info.nick_name
     *
     * @param nickName the value for tb_user_info.nick_name
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    public void setNickName(String nickName) {
        this.nickName = nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_info.password
     *
     * @return the value of tb_user_info.password
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_info.password
     *
     * @param password the value for tb_user_info.password
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_info.email
     *
     * @return the value of tb_user_info.email
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_info.email
     *
     * @param email the value for tb_user_info.email
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_info.gender
     *
     * @return the value of tb_user_info.gender
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    public Boolean getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_info.gender
     *
     * @param gender the value for tb_user_info.gender
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    public void setGender(Boolean gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_info.avatar_url
     *
     * @return the value of tb_user_info.avatar_url
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    public String getAvatarUrl() {
        return avatarUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_info.avatar_url
     *
     * @param avatarUrl the value for tb_user_info.avatar_url
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    public void setAvatarUrl(String avatarUrl) {
        this.avatarUrl = avatarUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_info.phone
     *
     * @return the value of tb_user_info.phone
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_info.phone
     *
     * @param phone the value for tb_user_info.phone
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_info.address
     *
     * @return the value of tb_user_info.address
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    public Integer getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_info.address
     *
     * @param address the value for tb_user_info.address
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    public void setAddress(Integer address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_info.company
     *
     * @return the value of tb_user_info.company
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    public String getCompany() {
        return company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_info.company
     *
     * @param company the value for tb_user_info.company
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    public void setCompany(String company) {
        this.company = company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_info.position
     *
     * @return the value of tb_user_info.position
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    public String getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_info.position
     *
     * @param position the value for tb_user_info.position
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    public void setPosition(String position) {
        this.position = position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_info.equipment
     *
     * @return the value of tb_user_info.equipment
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    public String getEquipment() {
        return equipment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_info.equipment
     *
     * @param equipment the value for tb_user_info.equipment
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    public void setEquipment(String equipment) {
        this.equipment = equipment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_info.style
     *
     * @return the value of tb_user_info.style
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    public Byte getStyle() {
        return style;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_info.style
     *
     * @param style the value for tb_user_info.style
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    public void setStyle(Byte style) {
        this.style = style;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_info.create_time
     *
     * @return the value of tb_user_info.create_time
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_info.create_time
     *
     * @param createTime the value for tb_user_info.create_time
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user_info.update_time
     *
     * @return the value of tb_user_info.update_time
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user_info.update_time
     *
     * @param updateTime the value for tb_user_info.update_time
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}