package com.uyoung.core.api.dao;

import com.uyoung.core.api.model.ActivityInfo;
import com.uyoung.core.api.model.ActivityInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ActivityInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_activity_info
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    int countByExample(ActivityInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_activity_info
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    int deleteByExample(ActivityInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_activity_info
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_activity_info
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    int insert(ActivityInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_activity_info
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    int insertSelective(ActivityInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_activity_info
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    List<ActivityInfo> selectByExample(ActivityInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_activity_info
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    ActivityInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_activity_info
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    int updateByExampleSelective(@Param("record") ActivityInfo record, @Param("example") ActivityInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_activity_info
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    int updateByExample(@Param("record") ActivityInfo record, @Param("example") ActivityInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_activity_info
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    int updateByPrimaryKeySelective(ActivityInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_activity_info
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    int updateByPrimaryKey(ActivityInfo record);
}