package com.uyoung.core.api.dao;

import com.uyoung.core.api.model.ActivitySignUp;
import com.uyoung.core.api.model.ActivitySignUpExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ActivitySignUpMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_activity_signup
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    int countByExample(ActivitySignUpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_activity_signup
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    int deleteByExample(ActivitySignUpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_activity_signup
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_activity_signup
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    int insert(ActivitySignUp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_activity_signup
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    int insertSelective(ActivitySignUp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_activity_signup
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    List<ActivitySignUp> selectByExample(ActivitySignUpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_activity_signup
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    ActivitySignUp selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_activity_signup
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    int updateByExampleSelective(@Param("record") ActivitySignUp record, @Param("example") ActivitySignUpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_activity_signup
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    int updateByExample(@Param("record") ActivitySignUp record, @Param("example") ActivitySignUpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_activity_signup
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    int updateByPrimaryKeySelective(ActivitySignUp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_activity_signup
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    int updateByPrimaryKey(ActivitySignUp record);
}