package com.uyoung.core.api.dao;

import com.uyoung.core.api.model.AlbumInfo;
import com.uyoung.core.api.model.AlbumInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AlbumInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_album_info
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    int countByExample(AlbumInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_album_info
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    int deleteByExample(AlbumInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_album_info
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_album_info
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    int insert(AlbumInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_album_info
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    int insertSelective(AlbumInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_album_info
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    List<AlbumInfo> selectByExample(AlbumInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_album_info
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    AlbumInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_album_info
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    int updateByExampleSelective(@Param("record") AlbumInfo record, @Param("example") AlbumInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_album_info
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    int updateByExample(@Param("record") AlbumInfo record, @Param("example") AlbumInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_album_info
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    int updateByPrimaryKeySelective(AlbumInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_album_info
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    int updateByPrimaryKey(AlbumInfo record);
}