package com.uyoung.core.api.dao;

import com.uyoung.core.api.model.MobileInfo;
import com.uyoung.core.api.model.MobileInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MobileInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_mobile_info
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    int countByExample(MobileInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_mobile_info
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    int deleteByExample(MobileInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_mobile_info
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_mobile_info
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    int insert(MobileInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_mobile_info
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    int insertSelective(MobileInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_mobile_info
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    List<MobileInfo> selectByExample(MobileInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_mobile_info
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    MobileInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_mobile_info
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    int updateByExampleSelective(@Param("record") MobileInfo record, @Param("example") MobileInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_mobile_info
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    int updateByExample(@Param("record") MobileInfo record, @Param("example") MobileInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_mobile_info
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    int updateByPrimaryKeySelective(MobileInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_mobile_info
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    int updateByPrimaryKey(MobileInfo record);
}