package com.uyoung.core.api.dao;

import com.uyoung.core.api.model.PhotoInfo;
import com.uyoung.core.api.model.PhotoInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PhotoInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_photo_info
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    int countByExample(PhotoInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_photo_info
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    int deleteByExample(PhotoInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_photo_info
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_photo_info
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    int insert(PhotoInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_photo_info
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    int insertSelective(PhotoInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_photo_info
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    List<PhotoInfo> selectByExample(PhotoInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_photo_info
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    PhotoInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_photo_info
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    int updateByExampleSelective(@Param("record") PhotoInfo record, @Param("example") PhotoInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_photo_info
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    int updateByExample(@Param("record") PhotoInfo record, @Param("example") PhotoInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_photo_info
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    int updateByPrimaryKeySelective(PhotoInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_photo_info
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    int updateByPrimaryKey(PhotoInfo record);
}