package com.uyoung.core.api.dao;

import com.uyoung.core.api.model.PhotoLike;
import com.uyoung.core.api.model.PhotoLikeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PhotoLikeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_photo_like
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    int countByExample(PhotoLikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_photo_like
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    int deleteByExample(PhotoLikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_photo_like
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_photo_like
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    int insert(PhotoLike record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_photo_like
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    int insertSelective(PhotoLike record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_photo_like
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    List<PhotoLike> selectByExample(PhotoLikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_photo_like
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    PhotoLike selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_photo_like
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    int updateByExampleSelective(@Param("record") PhotoLike record, @Param("example") PhotoLikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_photo_like
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    int updateByExample(@Param("record") PhotoLike record, @Param("example") PhotoLikeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_photo_like
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    int updateByPrimaryKeySelective(PhotoLike record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_photo_like
     *
     * @mbggenerated Sat Sep 19 17:42:07 CST 2015
     */
    int updateByPrimaryKey(PhotoLike record);
}